# Generated by Django 4.2.21 on 2025-06-21 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0003_bot_alter_exchange_exchange_type_botlog_bot_exchange_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchange',
            name='exchange_type',
            field=models.CharField(choices=[('', 'Select Exchange'), ('bybit', 'Bybit'), ('binance', 'Binance'), ('gateio', 'Gateio')], max_length=32),
        ),
    ]
