# Generated by Django 4.2.21 on 2025-06-21 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0004_alter_exchange_exchange_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchange',
            name='credentials_example',
            field=models.JSONField(blank=True, default=dict, help_text='Example of API credentials (key, secret, passphrase, etc)', null=True),
        ),
    ]
