# Generated by Django 4.2.21 on 2025-06-21 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0005_exchange_credentials_example'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exchange',
            name='credentials_example',
        ),
    ]
