# Generated by Django 4.2.21 on 2025-06-28 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0006_remove_exchange_credentials_example'),
    ]

    operations = [
        migrations.AddField(
            model_name='bot',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bot',
            name='position_size',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='bot',
            name='symbol',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
