# Generated by Django 4.2.21 on 2025-06-02 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='preferred_platforms',
        ),
    ]
